### ISSUE TITLE
Are `args.pos_label_freq` and `args.neg_label_freq` predefined?

### ISSUE THREAD

**Issue by hb-studying** [milkxie/SSMLL-CAP#2]
Are `args.pos_label_freq` and `args.neg_label_freq` predefined? I didn’t find any definitions for these two variables in the `run_CAP.py` file, nor did I see any process for calculating them in `run_warmup`. Based on the description in the paper, these two variables should be estimated from the labeled data, but it seems they aren’t provided in the code. Does the experiment assume that the positive and negative label ratios for all categories are already known?

**Comment by xiemk** [comment]
Thank you for your attention^^
Please see /lib/dataset/get_dataset.py

**Comment by hb-studying** [comment]
Thank you, I didn't look carefully enough before.ಥ⌣ಥ
